"""PHASE 5 — 임베딩 기반 유사 함수 후보 축소(17절).

모든 함수 쌍을 LLM에 넣지 않는다. 의미적으로 비슷한 쌍만 골라 PHASE 6에 넘긴다.
원안의 OpenAI embedding 대신 로컬 `sentence-transformers` 를 쓴다(9/12 AI 스택 결정).

threshold 는 고정하지 않는다. 17절 지시대로 저장소를 돌려보며 후보 수를 보고 정한다.
`--report` 로 threshold 별 후보 수 분포를 먼저 확인할 것.

사용법:
    py -m judge.embed repos/psf__requests --report
    py -m judge.embed repos/psf__requests --threshold=0.80 --json=cache/pairs.json
"""

import ast
import json
import re
import sys
from pathlib import Path

import numpy as np

from analyzer.collect import CollectError, _git
from judge.extract import MAX_FUNCTIONS, extract

# 로컬 실행. API 호출도 과금도 없다.
EMBED_MODEL = "all-MiniLM-L6-v2"

CACHE_DIR = Path(__file__).resolve().parent.parent / "cache" / "embeddings"

# 후보 수를 수십~100개 수준으로 제한한다(17절 목표).
DEFAULT_THRESHOLD = 0.80
MAX_PAIRS = 100
REPORT_THRESHOLDS = (0.70, 0.75, 0.80, 0.85, 0.90, 0.95)

# 너무 짧은 함수는 비교해도 의미가 없다.
# 문장 수는 빈 함수(pass, ...)만 걸러내는 하한이고, 실질적인 차단은 글자 수가 한다.
# 문장 수를 2로 두면 `return self.predict(peptides, n_flanks=...)` 같은
# 인자를 넘기는 override 가 걸러진다 — PHASE 1 이 검증한 T1 쌍이 실제로 그렇게 사라졌다.
MIN_BODY_STATEMENTS = 1
MIN_SOURCE_CHARS = 80

# 거의 완전히 같은 코드는 물어볼 "차이"가 없다(17절 "의미 없는 복사본" 제외).
# 이 상한이 없으면 후보 상위가 복붙 wrapper 로 차고,
# 정작 물어볼 가치가 있는 "비슷한데 다른" 쌍이 상한 밖으로 밀려난다.
MAX_SIMILARITY = 0.97

# 한 함수가 등장할 수 있는 후보 쌍의 수. 복붙 무리가 후보를 독식하는 것을 막는다.
MAX_PER_FUNCTION = 1

# 자동 생성 코드 표식. 원저자가 손으로 쓴 코드가 아니므로 인수인계 질문 대상이 아니다.
GENERATED_MARKERS = ("do not edit", "auto-generated", "autogenerated",
                     "generated by", "@generated")


def _normalize(source: str) -> str:
    """중복 판정용 정규화 — 독스트링/주석/공백 제거."""
    source = re.sub(r'("""|\'\'\')[\s\S]*?\1', "", source)
    source = re.sub(r"#.*", "", source)
    return re.sub(r"\s+", " ", source).strip()


def is_trivial(func: dict) -> bool:
    """17절 후보 필터 — 너무 짧은 함수, getter/setter, 테스트 helper, 생성 코드."""
    if func["is_test"]:
        return True
    if len(func["source"]) < MIN_SOURCE_CHARS:
        return True
    if any(m in func["source"][:400].lower() for m in GENERATED_MARKERS):
        return True

    try:
        tree = ast.parse(func["source"].lstrip())
    except (SyntaxError, ValueError):
        # 메서드는 들여쓰기 때문에 단독 파싱이 안 될 수 있다. 길이 기준만 적용한다.
        return False

    node = tree.body[0] if tree.body else None
    if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        return False

    body = node.body
    if body and isinstance(body[0], ast.Expr) and isinstance(body[0].value, ast.Constant) \
            and isinstance(body[0].value.value, str):
        body = body[1:]

    # 문장은 중첩까지 세야 한다. 최상위만 세면 "for 루프 하나로 된 20줄 함수"가
    # "return self._x" 와 같은 1개로 잡혀 실제 후보가 통째로 걸러진다.
    statements = sum(len([n for n in ast.walk(stmt) if isinstance(n, ast.stmt)]) for stmt in body)
    if statements < MIN_BODY_STATEMENTS:
        # 한 줄짜리 getter/setter, return self._x, pass 등
        return True

    return False


def load_model():
    """sentence-transformers 모델을 읽는다. 첫 실행은 모델을 내려받는다(약 90MB)."""
    try:
        from sentence_transformers import SentenceTransformer
    except ImportError:
        raise CollectError(
            "sentence-transformers 가 설치되어 있지 않습니다.\n"
            "  pip install -r requirements.txt"
        )
    return SentenceTransformer(EMBED_MODEL)


def embed(functions: list[dict], head_sha: str, repo_name: str) -> np.ndarray:
    """함수 source 를 벡터로 만든다. 같은 commit SHA면 캐시를 재사용한다(17절)."""
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    cache_path = CACHE_DIR / f"{repo_name}_{head_sha[:12]}_{EMBED_MODEL}.npz"

    keys = [f"{f['file']}:{f['start_line']}:{f['name']}" for f in functions]

    if cache_path.exists():
        cached = np.load(cache_path, allow_pickle=True)
        # 캐시가 지금 함수 목록과 정확히 같을 때만 쓴다. 어긋나면 다시 계산한다.
        if list(cached["keys"]) == keys:
            print(f"임베딩 캐시 사용: {cache_path.name}")
            return cached["vectors"]

    model = load_model()
    vectors = model.encode([f["source"] for f in functions],
                           batch_size=32, show_progress_bar=False,
                           normalize_embeddings=True)
    vectors = np.asarray(vectors, dtype=np.float32)
    np.savez_compressed(cache_path, vectors=vectors, keys=np.array(keys))
    print(f"임베딩 {len(functions)}개 계산, 캐시 저장: {cache_path.name}")
    return vectors


def similar_pairs(functions: list[dict], vectors: np.ndarray, threshold: float,
                  max_pairs: int = MAX_PAIRS,
                  max_similarity: float = MAX_SIMILARITY,
                  max_per_function: int = MAX_PER_FUNCTION) -> list[dict]:
    """cosine similarity 가 [threshold, max_similarity] 구간인 쌍을 돌려준다.

    벡터는 정규화되어 있어 내적이 곧 cosine.
    상한을 두는 이유는 위쪽이 복붙 코드로 차서 정작 물어볼 쌍이 밀려나기 때문이다.
    """
    sim = vectors @ vectors.T
    # 자기 자신과 아래쪽 삼각형은 제외 — 같은 쌍을 두 번 세지 않는다.
    iu = np.triu_indices(len(functions), k=1)
    scores = sim[iu]

    hits = np.flatnonzero((scores >= threshold) & (scores <= max_similarity))
    order = hits[np.argsort(-scores[hits])]

    seen_groups: set = set()
    used: dict = {}
    pairs = []

    for idx in order:
        a, b = functions[iu[0][idx]], functions[iu[1][idx]]
        if a["file"] == b["file"] and a["name"] == b["name"]:
            continue

        # 한 함수가 후보를 독식하지 못하게 막는다. 이게 없으면 wrapper 한 무리가
        # 상한 100개를 전부 채우고, 정작 물어볼 쌍이 밀려난다.
        ka = (a["file"], a["name"], a["start_line"])
        kb = (b["file"], b["name"], b["start_line"])
        if used.get(ka, 0) >= max_per_function or used.get(kb, 0) >= max_per_function:
            continue

        na, nb = _normalize(a["source"]), _normalize(b["source"])
        # 완전히 같은 코드는 물어볼 "차이"가 없다. ①②는 차이를 묻는 기능이다(17절 복사본 제외).
        if na == nb:
            continue
        # 같은 코드 쌍이 여러 파일에 반복되면 대표 한 쌍만 남긴다.
        group = tuple(sorted((na, nb)))
        if group in seen_groups:
            continue
        seen_groups.add(group)
        used[ka] = used.get(ka, 0) + 1
        used[kb] = used.get(kb, 0) + 1

        pairs.append({
            "similarity": round(float(scores[idx]), 4),
            "a": {k: a[k] for k in ("file", "name", "start_line", "end_line", "signature")},
            "b": {k: b[k] for k in ("file", "name", "start_line", "end_line", "signature")},
        })
        if len(pairs) >= max_pairs:
            break

    return pairs


def build(clone_path: Path, threshold: float = DEFAULT_THRESHOLD,
          max_pairs: int = MAX_PAIRS) -> tuple[list[dict], list[dict], np.ndarray]:
    """(후보 쌍, 필터 통과 함수, 벡터) 를 돌려준다."""
    if not (clone_path / ".git").is_dir():
        raise CollectError(f"git 저장소가 아닙니다: {clone_path}")

    head_sha = _git(["rev-parse", "HEAD"], cwd=clone_path)
    functions = extract(clone_path, max_functions=MAX_FUNCTIONS)
    kept = [f for f in functions if not is_trivial(f)]

    print(f"함수 {len(functions)}개 → 필터 통과 {len(kept)}개 "
          f"(제외 {len(functions) - len(kept)})")
    if not kept:
        return [], [], np.zeros((0, 0), dtype=np.float32)

    vectors = embed(kept, head_sha, clone_path.name)
    return similar_pairs(kept, vectors, threshold, max_pairs), kept, vectors


def main() -> int:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if len(args) != 1:
        print("사용법: py -m judge.embed repos/owner__repo "
              "[--report] [--threshold=0.80] [--json=파일]", file=sys.stderr)
        return 2

    threshold = float(next((a.split("=", 1)[1] for a in sys.argv
                            if a.startswith("--threshold=")), DEFAULT_THRESHOLD))

    try:
        # --report 는 상한 없이 모아 분포를 본다. threshold 를 정하기 위한 관측이다.
        report = "--report" in sys.argv
        pairs, kept, vectors = build(Path(args[0]),
                                     threshold=min(REPORT_THRESHOLDS) if report else threshold,
                                     max_pairs=10 ** 6 if report else MAX_PAIRS)
    except CollectError as exc:
        print(f"임베딩 실패: {exc}", file=sys.stderr)
        return 1

    if report:
        print("\nthreshold 별 후보 수 (17절: 수십~100개가 목표)")
        for t in REPORT_THRESHOLDS:
            n = sum(1 for p in pairs if p["similarity"] >= t)
            mark = "  ← 목표 구간" if 20 <= n <= 100 else ""
            print(f"  >= {t:.2f} : {n:5d} 쌍{mark}")
        return 0

    print(f"\nthreshold {threshold} → 후보 {len(pairs)}쌍")
    for p in pairs[:10]:
        print(f"  {p['similarity']:.3f}  {p['a']['file']}:{p['a']['name']}"
              f"  <->  {p['b']['file']}:{p['b']['name']}")

    out = next((a.split("=", 1)[1] for a in sys.argv if a.startswith("--json=")), None)
    if out:
        path = Path(out)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(pairs, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"저장: {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
